name: Generate JSON Data

on:
  schedule:
    - cron: '0 5 * * *' # This will run the action once a day at 5 AM UTC
  workflow_dispatch: # Allows for manual execution from the GitHub UI

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Generate Upcoming MLB JSON
        run: python get_data/MLB/upcoming_games.py

      - name: Generate Yesterday's MLB JSON
        run: python get_data/MLB/yesterdays_games.py

      - name: Generate Hourly Weather JSON
        run: python get_data/weather/hourly.py

      - name: Generate Weekly Weather JSON
        run: python get_data/weather/weekly.py     

      - name: Commit and push JSON files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Update JSON files"
          branch: "main"